name: telegram-bot


services:
  bot:
    image: ghcr.io/${GHCR_USER}/telegram-bot:latest
    env_file: .env
    volumes:
      - /opt/telegram-bot/data:/app/database  # <- тут хранишь sqlite/json/файлы
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.5"

# volumes:
#   bot-data: