# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/telegram-bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (compose.yaml needed to upload)
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload compose.yaml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "compose.yaml"
          target: "/opt/telegram-bot/"
          strip_components: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          IMAGE: ghcr.io/${{ secrets.GHCR_USER }}/telegram-bot:latest
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          envs: GHCR_USER,GHCR_PAT,BOT_TOKEN,IMAGE
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            sudo mkdir -p /opt/telegram-bot
            cd /opt/telegram-bot

            # Создаём/обновляем .env без утечек
            (umask 077; cat > .env << 'EOF'
            BOT_TOKEN=${BOT_TOKEN}
            GHCR_USER=${GHCR_USER}
            GHCR_PAT=${GHCR_PAT}
            TZ=Europe/Moscow
            EOF
            )

            # Устанавливаем/проверяем Docker + Compose v2 (если уже есть — шаги пропустятся)
            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER || true
            fi

            # Логин в GHCR и обновление образа
            echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin

            # Обновляем image ссылку в compose.yaml (GHCR_USER как var)
            if ! grep -q "${GHCR_USER}" compose.yaml; then
              sed -i "s#ghcr.io/.*/telegram-bot:latest#${IMAGE}#g" compose.yaml
            fi

            docker pull "${IMAGE}"
            docker compose up -d --remove-orphans
            docker image prune -f