# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/telegram-bot
  GHCR_USER: ${{ secrets.GHCR_USER }}
  GHCR_PAT: ${{ secrets.GHCR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (compose.yaml needed to upload)
        uses: actions/checkout@v4

      - name: Upload compose.yaml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "compose.yaml"
          target: "/opt/telegram-bot/database"
          strip_components: 0

      - name: Check GHCR secrets
        run: |
          if [ -z "${{ secrets.GHCR_USER }}" ] || [ -z "${{ secrets.GHCR_PAT }}" ]; then
            echo "GHCR_USER or GHCR_PAT is missing!"
            exit 1
          fi

      - name: Docker Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          IMAGE: ghcr.io/${{ secrets.GHCR_USER }}/telegram-bot:latest
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: GHCR_USER,GHCR_PAT,BOT_TOKEN,IMAGE
          script: |
            set -euo pipefail

            sudo mkdir -p /opt/telegram-bot
            cd /opt/telegram-bot

            # Check secrets before login
            if [ -z "${GHCR_USER}" ] || [ -z "${GHCR_PAT}" ]; then
              echo "GHCR_USER or GHCR_PAT is missing!"
              exit 1
            fi

            (umask 077; cat > .env <<EOF
            BOT_TOKEN=${BOT_TOKEN}
            TZ=Europe/Paris
            EOF
            )

            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
              REMOTE_USER="$(id -un)"
              sudo usermod -aG docker "$REMOTE_USER" || true
            fi

            # Docker login with error handling
            echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin || {
              echo "Docker login to GHCR failed. Check GHCR_PAT and GHCR_USER!";
              exit 1;
            }

            if ! grep -q "${GHCR_USER}" compose.yaml; then
              sed -i "s#ghcr.io/.*/telegram-bot:latest#${IMAGE}#g" compose.yaml
            fi

            docker pull "${IMAGE}"
            docker compose up -d --remove-orphans
            docker image prune -f